// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.4.0
// source: gameserver/gameservice.proto

package gameserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	CreateGameService(ctx context.Context, in *CreateGameServiceRequest, opts ...grpc.CallOption) (*CreateGameServiceReply, error)
	TestApi(ctx context.Context, in *TestApiReq, opts ...grpc.CallOption) (*TestApiRes, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) CreateGameService(ctx context.Context, in *CreateGameServiceRequest, opts ...grpc.CallOption) (*CreateGameServiceReply, error) {
	out := new(CreateGameServiceReply)
	err := c.cc.Invoke(ctx, "/api.gameserver.GameService/CreateGameService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) TestApi(ctx context.Context, in *TestApiReq, opts ...grpc.CallOption) (*TestApiRes, error) {
	out := new(TestApiRes)
	err := c.cc.Invoke(ctx, "/api.gameserver.GameService/TestApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	CreateGameService(context.Context, *CreateGameServiceRequest) (*CreateGameServiceReply, error)
	TestApi(context.Context, *TestApiReq) (*TestApiRes, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) CreateGameService(context.Context, *CreateGameServiceRequest) (*CreateGameServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGameService not implemented")
}
func (UnimplementedGameServiceServer) TestApi(context.Context, *TestApiReq) (*TestApiRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestApi not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_CreateGameService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateGameService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.gameserver.GameService/CreateGameService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateGameService(ctx, req.(*CreateGameServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_TestApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).TestApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.gameserver.GameService/TestApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).TestApi(ctx, req.(*TestApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gameserver.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGameService",
			Handler:    _GameService_CreateGameService_Handler,
		},
		{
			MethodName: "TestApi",
			Handler:    _GameService_TestApi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gameserver/gameservice.proto",
}
