// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	biz2 "dmgame/services/notiservices/internal/biz"
	conf2 "dmgame/services/notiservices/internal/conf"
	data2 "dmgame/services/notiservices/internal/data"
	server2 "dmgame/services/notiservices/internal/server"
	service2 "dmgame/services/notiservices/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf2.Server, confData *conf2.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data2.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data2.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz2.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service2.NewGreeterService(greeterUsecase)
	httpServer := server2.NewHTTPServer(confServer, greeterService, logger)
	grpcServer := server2.NewGRPCServer(confServer, greeterService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
