// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: api/routerservice/routerservice.proto

package routerserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRouterServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRouterServiceRequest) Reset() {
	*x = CreateRouterServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_routerservice_routerservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRouterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouterServiceRequest) ProtoMessage() {}

func (x *CreateRouterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_routerservice_routerservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouterServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateRouterServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_routerservice_routerservice_proto_rawDescGZIP(), []int{0}
}

type CreateRouterServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRouterServiceReply) Reset() {
	*x = CreateRouterServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_routerservice_routerservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRouterServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouterServiceReply) ProtoMessage() {}

func (x *CreateRouterServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_routerservice_routerservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouterServiceReply.ProtoReflect.Descriptor instead.
func (*CreateRouterServiceReply) Descriptor() ([]byte, []int) {
	return file_api_routerservice_routerservice_proto_rawDescGZIP(), []int{1}
}

var File_api_routerservice_routerservice_proto protoreflect.FileDescriptor

var file_api_routerservice_routerservice_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x32, 0x80, 0x01, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3a, 0x0a, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x24, 0x64, 0x6d,
	0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x3b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_routerservice_routerservice_proto_rawDescOnce sync.Once
	file_api_routerservice_routerservice_proto_rawDescData = file_api_routerservice_routerservice_proto_rawDesc
)

func file_api_routerservice_routerservice_proto_rawDescGZIP() []byte {
	file_api_routerservice_routerservice_proto_rawDescOnce.Do(func() {
		file_api_routerservice_routerservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_routerservice_routerservice_proto_rawDescData)
	})
	return file_api_routerservice_routerservice_proto_rawDescData
}

var file_api_routerservice_routerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_routerservice_routerservice_proto_goTypes = []interface{}{
	(*CreateRouterServiceRequest)(nil), // 0: api.routerserver.CreateRouterServiceRequest
	(*CreateRouterServiceReply)(nil),   // 1: api.routerserver.CreateRouterServiceReply
}
var file_api_routerservice_routerservice_proto_depIdxs = []int32{
	0, // 0: api.routerserver.RouterService.CreateRouterService:input_type -> api.routerserver.CreateRouterServiceRequest
	1, // 1: api.routerserver.RouterService.CreateRouterService:output_type -> api.routerserver.CreateRouterServiceReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_routerservice_routerservice_proto_init() }
func file_api_routerservice_routerservice_proto_init() {
	if File_api_routerservice_routerservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_routerservice_routerservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRouterServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_routerservice_routerservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRouterServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_routerservice_routerservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_routerservice_routerservice_proto_goTypes,
		DependencyIndexes: file_api_routerservice_routerservice_proto_depIdxs,
		MessageInfos:      file_api_routerservice_routerservice_proto_msgTypes,
	}.Build()
	File_api_routerservice_routerservice_proto = out.File
	file_api_routerservice_routerservice_proto_rawDesc = nil
	file_api_routerservice_routerservice_proto_goTypes = nil
	file_api_routerservice_routerservice_proto_depIdxs = nil
}
