// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.4.0
// source: notiserver/notiservice.proto

package notiserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNotiServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateNotiServiceRequest) Reset() {
	*x = CreateNotiServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notiserver_notiservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotiServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotiServiceRequest) ProtoMessage() {}

func (x *CreateNotiServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notiserver_notiservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotiServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateNotiServiceRequest) Descriptor() ([]byte, []int) {
	return file_notiserver_notiservice_proto_rawDescGZIP(), []int{0}
}

type CreateNotiServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateNotiServiceReply) Reset() {
	*x = CreateNotiServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notiserver_notiservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotiServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotiServiceReply) ProtoMessage() {}

func (x *CreateNotiServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_notiserver_notiservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotiServiceReply.ProtoReflect.Descriptor instead.
func (*CreateNotiServiceReply) Descriptor() ([]byte, []int) {
	return file_notiserver_notiservice_proto_rawDescGZIP(), []int{1}
}

var File_notiserver_notiservice_proto protoreflect.FileDescriptor

var file_notiserver_notiservice_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6e, 0x6f, 0x74, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6e, 0x6f, 0x74,
	0x69, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x1a,
	0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0x74, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x69, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x6f, 0x74, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x34, 0x0a, 0x0e, 0x61, 0x70,
	0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x20,
	0x64, 0x6d, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x3b, 0x6e, 0x6f, 0x74, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notiserver_notiservice_proto_rawDescOnce sync.Once
	file_notiserver_notiservice_proto_rawDescData = file_notiserver_notiservice_proto_rawDesc
)

func file_notiserver_notiservice_proto_rawDescGZIP() []byte {
	file_notiserver_notiservice_proto_rawDescOnce.Do(func() {
		file_notiserver_notiservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_notiserver_notiservice_proto_rawDescData)
	})
	return file_notiserver_notiservice_proto_rawDescData
}

var file_notiserver_notiservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notiserver_notiservice_proto_goTypes = []interface{}{
	(*CreateNotiServiceRequest)(nil), // 0: api.notiserver.CreateNotiServiceRequest
	(*CreateNotiServiceReply)(nil),   // 1: api.notiserver.CreateNotiServiceReply
}
var file_notiserver_notiservice_proto_depIdxs = []int32{
	0, // 0: api.notiserver.NotiService.CreateNotiService:input_type -> api.notiserver.CreateNotiServiceRequest
	1, // 1: api.notiserver.NotiService.CreateNotiService:output_type -> api.notiserver.CreateNotiServiceReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notiserver_notiservice_proto_init() }
func file_notiserver_notiservice_proto_init() {
	if File_notiserver_notiservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notiserver_notiservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotiServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notiserver_notiservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotiServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notiserver_notiservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notiserver_notiservice_proto_goTypes,
		DependencyIndexes: file_notiserver_notiservice_proto_depIdxs,
		MessageInfos:      file_notiserver_notiservice_proto_msgTypes,
	}.Build()
	File_notiserver_notiservice_proto = out.File
	file_notiserver_notiservice_proto_rawDesc = nil
	file_notiserver_notiservice_proto_goTypes = nil
	file_notiserver_notiservice_proto_depIdxs = nil
}
