// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.4.0
// source: notiserver/notiservice.proto

package notiserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotiServiceClient is the client API for NotiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotiServiceClient interface {
	CreateNotiService(ctx context.Context, in *CreateNotiServiceRequest, opts ...grpc.CallOption) (*CreateNotiServiceReply, error)
}

type notiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotiServiceClient(cc grpc.ClientConnInterface) NotiServiceClient {
	return &notiServiceClient{cc}
}

func (c *notiServiceClient) CreateNotiService(ctx context.Context, in *CreateNotiServiceRequest, opts ...grpc.CallOption) (*CreateNotiServiceReply, error) {
	out := new(CreateNotiServiceReply)
	err := c.cc.Invoke(ctx, "/api.notiserver.NotiService/CreateNotiService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotiServiceServer is the server API for NotiService service.
// All implementations must embed UnimplementedNotiServiceServer
// for forward compatibility
type NotiServiceServer interface {
	CreateNotiService(context.Context, *CreateNotiServiceRequest) (*CreateNotiServiceReply, error)
	mustEmbedUnimplementedNotiServiceServer()
}

// UnimplementedNotiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotiServiceServer struct {
}

func (UnimplementedNotiServiceServer) CreateNotiService(context.Context, *CreateNotiServiceRequest) (*CreateNotiServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotiService not implemented")
}
func (UnimplementedNotiServiceServer) mustEmbedUnimplementedNotiServiceServer() {}

// UnsafeNotiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotiServiceServer will
// result in compilation errors.
type UnsafeNotiServiceServer interface {
	mustEmbedUnimplementedNotiServiceServer()
}

func RegisterNotiServiceServer(s grpc.ServiceRegistrar, srv NotiServiceServer) {
	s.RegisterService(&NotiService_ServiceDesc, srv)
}

func _NotiService_CreateNotiService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotiServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotiServiceServer).CreateNotiService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.notiserver.NotiService/CreateNotiService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotiServiceServer).CreateNotiService(ctx, req.(*CreateNotiServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotiService_ServiceDesc is the grpc.ServiceDesc for NotiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.notiserver.NotiService",
	HandlerType: (*NotiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNotiService",
			Handler:    _NotiService_CreateNotiService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notiserver/notiservice.proto",
}
